// flow-typed signature: c44080c334c0ce357a851f12a824937f
// flow-typed version: <<STUB>>/rambler-ui_vvx.x.x/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rambler-ui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rambler-ui' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rambler-ui/Avatar/Avatar' {
  declare module.exports: any;
}

declare module 'rambler-ui/Avatar/index' {
  declare module.exports: any;
}

declare module 'rambler-ui/Button/Button' {
  declare module.exports: any;
}

declare module 'rambler-ui/Button/index' {
  declare module.exports: any;
}

declare module 'rambler-ui/Checkbox/Checkbox' {
  declare module.exports: any;
}

declare module 'rambler-ui/Checkbox/index' {
  declare module.exports: any;
}

declare module 'rambler-ui/ComplexSearch/ComplexSearch' {
  declare module.exports: any;
}

declare module 'rambler-ui/ComplexSearch/index' {
  declare module.exports: any;
}

declare module 'rambler-ui/ComplexSearch/SuggestItem' {
  declare module.exports: any;
}

declare module 'rambler-ui/constants/context' {
  declare module.exports: any;
}

declare module 'rambler-ui/constants/keys' {
  declare module.exports: any;
}

declare module 'rambler-ui/constants/overlay' {
  declare module.exports: any;
}

declare module 'rambler-ui/constants/z-indexes' {
  declare module.exports: any;
}

declare module 'rambler-ui/Dropdown/Dropdown' {
  declare module.exports: any;
}

declare module 'rambler-ui/Dropdown/index' {
  declare module.exports: any;
}

declare module 'rambler-ui/events/OnClickOutside' {
  declare module.exports: any;
}

declare module 'rambler-ui/FieldGroup/FieldGroup' {
  declare module.exports: any;
}

declare module 'rambler-ui/FieldGroup/index' {
  declare module.exports: any;
}

declare module 'rambler-ui/FormGroup/FormGroup' {
  declare module.exports: any;
}

declare module 'rambler-ui/FormGroup/index' {
  declare module.exports: any;
}

declare module 'rambler-ui/Hint/Hint' {
  declare module.exports: any;
}

declare module 'rambler-ui/Hint/index' {
  declare module.exports: any;
}

declare module 'rambler-ui/hoc/provide-render-to-layer' {
  declare module.exports: any;
}

declare module 'rambler-ui/hoc/render-to-layer' {
  declare module.exports: any;
}

declare module 'rambler-ui/hoc/window-events' {
  declare module.exports: any;
}

declare module 'rambler-ui/hoc/z-index-stack' {
  declare module.exports: any;
}

declare module 'rambler-ui/IconButton/IconButton' {
  declare module.exports: any;
}

declare module 'rambler-ui/IconButton/index' {
  declare module.exports: any;
}

declare module 'rambler-ui/icons/forms/AddIcon' {
  declare module.exports: any;
}

declare module 'rambler-ui/icons/forms/BlockIcon' {
  declare module.exports: any;
}

declare module 'rambler-ui/icons/forms/BookIcon' {
  declare module.exports: any;
}

declare module 'rambler-ui/icons/forms/ChevronLeftIcon' {
  declare module.exports: any;
}

declare module 'rambler-ui/icons/forms/ChevronRightIcon' {
  declare module.exports: any;
}

declare module 'rambler-ui/icons/forms/ClearIcon' {
  declare module.exports: any;
}

declare module 'rambler-ui/icons/forms/ClosedEyeIcon' {
  declare module.exports: any;
}

declare module 'rambler-ui/icons/forms/CreditCardIcon' {
  declare module.exports: any;
}

declare module 'rambler-ui/icons/forms/EditIcon' {
  declare module.exports: any;
}

declare module 'rambler-ui/icons/forms/EllipsisIcon' {
  declare module.exports: any;
}

declare module 'rambler-ui/icons/forms/EmailIcon' {
  declare module.exports: any;
}

declare module 'rambler-ui/icons/forms/Eye' {
  declare module.exports: any;
}

declare module 'rambler-ui/icons/forms/FaceIcon' {
  declare module.exports: any;
}

declare module 'rambler-ui/icons/forms/HoldIcon' {
  declare module.exports: any;
}

declare module 'rambler-ui/icons/forms/index' {
  declare module.exports: any;
}

declare module 'rambler-ui/icons/forms/InfoIcon' {
  declare module.exports: any;
}

declare module 'rambler-ui/icons/forms/KeyboardIcon' {
  declare module.exports: any;
}

declare module 'rambler-ui/icons/forms/LockIcon' {
  declare module.exports: any;
}

declare module 'rambler-ui/icons/forms/LockOpenIcon' {
  declare module.exports: any;
}

declare module 'rambler-ui/icons/forms/LockOutlineIcon' {
  declare module.exports: any;
}

declare module 'rambler-ui/icons/forms/PhoneIcon' {
  declare module.exports: any;
}

declare module 'rambler-ui/icons/forms/PhotoCameraIcon' {
  declare module.exports: any;
}

declare module 'rambler-ui/icons/forms/QuestionIcon' {
  declare module.exports: any;
}

declare module 'rambler-ui/icons/forms/RefreshIcon' {
  declare module.exports: any;
}

declare module 'rambler-ui/icons/forms/RemoveIcon' {
  declare module.exports: any;
}

declare module 'rambler-ui/icons/forms/SearchIcon' {
  declare module.exports: any;
}

declare module 'rambler-ui/icons/forms/SettingsIcon' {
  declare module.exports: any;
}

declare module 'rambler-ui/icons/forms/TickIcon' {
  declare module.exports: any;
}

declare module 'rambler-ui/icons/forms/UndoIcon' {
  declare module.exports: any;
}

declare module 'rambler-ui/icons/forms/WizardIcon' {
  declare module.exports: any;
}

declare module 'rambler-ui/icons/index' {
  declare module.exports: any;
}

declare module 'rambler-ui/icons/profiles/ChampionatIcon' {
  declare module.exports: any;
}

declare module 'rambler-ui/icons/profiles/FacebookIcon' {
  declare module.exports: any;
}

declare module 'rambler-ui/icons/profiles/GoogleIcon' {
  declare module.exports: any;
}

declare module 'rambler-ui/icons/profiles/index' {
  declare module.exports: any;
}

declare module 'rambler-ui/icons/profiles/InstagramIcon' {
  declare module.exports: any;
}

declare module 'rambler-ui/icons/profiles/LivejournalIcon' {
  declare module.exports: any;
}

declare module 'rambler-ui/icons/profiles/MailruIcon' {
  declare module.exports: any;
}

declare module 'rambler-ui/icons/profiles/OdnoklassnikiIcon' {
  declare module.exports: any;
}

declare module 'rambler-ui/icons/profiles/PgumosruIcon' {
  declare module.exports: any;
}

declare module 'rambler-ui/icons/profiles/PhoneIcon' {
  declare module.exports: any;
}

declare module 'rambler-ui/icons/profiles/RamblerIcon' {
  declare module.exports: any;
}

declare module 'rambler-ui/icons/profiles/TwitterIcon' {
  declare module.exports: any;
}

declare module 'rambler-ui/icons/profiles/VkontakteIcon' {
  declare module.exports: any;
}

declare module 'rambler-ui/icons/services/index' {
  declare module.exports: any;
}

declare module 'rambler-ui/icons/services/RamblerAutoIcon' {
  declare module.exports: any;
}

declare module 'rambler-ui/icons/services/RamblerMailIcon' {
  declare module.exports: any;
}

declare module 'rambler-ui/icons/services/RamblerMoneyIcon' {
  declare module.exports: any;
}

declare module 'rambler-ui/icons/SvgIcon/index' {
  declare module.exports: any;
}

declare module 'rambler-ui/icons/SvgIcon/SvgIcon' {
  declare module.exports: any;
}

declare module 'rambler-ui/Input/index' {
  declare module.exports: any;
}

declare module 'rambler-ui/Input/Input' {
  declare module.exports: any;
}

declare module 'rambler-ui/InputStatus/index' {
  declare module.exports: any;
}

declare module 'rambler-ui/InputStatus/InputStatus' {
  declare module.exports: any;
}

declare module 'rambler-ui/Loader/index' {
  declare module.exports: any;
}

declare module 'rambler-ui/Loader/Loader' {
  declare module.exports: any;
}

declare module 'rambler-ui/Menu/index' {
  declare module.exports: any;
}

declare module 'rambler-ui/Menu/Menu' {
  declare module.exports: any;
}

declare module 'rambler-ui/Menu/MenuItem' {
  declare module.exports: any;
}

declare module 'rambler-ui/Notification/index' {
  declare module.exports: any;
}

declare module 'rambler-ui/Notification/Notification' {
  declare module.exports: any;
}

declare module 'rambler-ui/Notification/provideNotification' {
  declare module.exports: any;
}

declare module 'rambler-ui/Overlay/FixedOverlay' {
  declare module.exports: any;
}

declare module 'rambler-ui/Overlay/index' {
  declare module.exports: any;
}

declare module 'rambler-ui/Overlay/RelativeOverlay' {
  declare module.exports: any;
}

declare module 'rambler-ui/Pagination/index' {
  declare module.exports: any;
}

declare module 'rambler-ui/Pagination/Pagination' {
  declare module.exports: any;
}

declare module 'rambler-ui/Popup/index' {
  declare module.exports: any;
}

declare module 'rambler-ui/Popup/Popup' {
  declare module.exports: any;
}

declare module 'rambler-ui/Popup/providePopup' {
  declare module.exports: any;
}

declare module 'rambler-ui/Radio/index' {
  declare module.exports: any;
}

declare module 'rambler-ui/Radio/RadioButton' {
  declare module.exports: any;
}

declare module 'rambler-ui/Radio/RadioButtonGroup' {
  declare module.exports: any;
}

declare module 'rambler-ui/Select/index' {
  declare module.exports: any;
}

declare module 'rambler-ui/Select/Select' {
  declare module.exports: any;
}

declare module 'rambler-ui/SideNav/index' {
  declare module.exports: any;
}

declare module 'rambler-ui/SideNav/SideNav' {
  declare module.exports: any;
}

declare module 'rambler-ui/SideNav/SideNavItem' {
  declare module.exports: any;
}

declare module 'rambler-ui/Snackbar/index' {
  declare module.exports: any;
}

declare module 'rambler-ui/Snackbar/provideSnackbar' {
  declare module.exports: any;
}

declare module 'rambler-ui/Snackbar/Snackbar' {
  declare module.exports: any;
}

declare module 'rambler-ui/Spinner/index' {
  declare module.exports: any;
}

declare module 'rambler-ui/Spinner/Spinner' {
  declare module.exports: any;
}

declare module 'rambler-ui/style/imports' {
  declare module.exports: any;
}

declare module 'rambler-ui/style/mixins' {
  declare module.exports: any;
}

declare module 'rambler-ui/Switcher/index' {
  declare module.exports: any;
}

declare module 'rambler-ui/Switcher/Switcher' {
  declare module.exports: any;
}

declare module 'rambler-ui/Tabs/index' {
  declare module.exports: any;
}

declare module 'rambler-ui/Tabs/Tabs' {
  declare module.exports: any;
}

declare module 'rambler-ui/Tabs/TabsItem' {
  declare module.exports: any;
}

declare module 'rambler-ui/TagsInput/index' {
  declare module.exports: any;
}

declare module 'rambler-ui/TagsInput/TagsInput' {
  declare module.exports: any;
}

declare module 'rambler-ui/TagsInput/TagsInputItem' {
  declare module.exports: any;
}

declare module 'rambler-ui/Textarea/index' {
  declare module.exports: any;
}

declare module 'rambler-ui/Textarea/Textarea' {
  declare module.exports: any;
}

declare module 'rambler-ui/theme/base/colors' {
  declare module.exports: any;
}

declare module 'rambler-ui/theme/base/i18n' {
  declare module.exports: any;
}

declare module 'rambler-ui/theme/base/index' {
  declare module.exports: any;
}

declare module 'rambler-ui/theme/champ/colors' {
  declare module.exports: any;
}

declare module 'rambler-ui/theme/champ/i18n' {
  declare module.exports: any;
}

declare module 'rambler-ui/theme/champ/index' {
  declare module.exports: any;
}

declare module 'rambler-ui/theme/index' {
  declare module.exports: any;
}

declare module 'rambler-ui/Toggle/index' {
  declare module.exports: any;
}

declare module 'rambler-ui/Toggle/Toggle' {
  declare module.exports: any;
}

declare module 'rambler-ui/Toggle/ToggleOption' {
  declare module.exports: any;
}

declare module 'rambler-ui/Tooltip/index' {
  declare module.exports: any;
}

declare module 'rambler-ui/Tooltip/Tooltip' {
  declare module.exports: any;
}

declare module 'rambler-ui/Typography/Description' {
  declare module.exports: any;
}

declare module 'rambler-ui/Typography/Epigraph' {
  declare module.exports: any;
}

declare module 'rambler-ui/Typography/GalleryDescription' {
  declare module.exports: any;
}

declare module 'rambler-ui/Typography/H1' {
  declare module.exports: any;
}

declare module 'rambler-ui/Typography/H2' {
  declare module.exports: any;
}

declare module 'rambler-ui/Typography/H3' {
  declare module.exports: any;
}

declare module 'rambler-ui/Typography/index' {
  declare module.exports: any;
}

declare module 'rambler-ui/Typography/List' {
  declare module.exports: any;
}

declare module 'rambler-ui/Typography/PhotoSource' {
  declare module.exports: any;
}

declare module 'rambler-ui/Typography/Quote' {
  declare module.exports: any;
}

declare module 'rambler-ui/Typography/Source' {
  declare module.exports: any;
}

declare module 'rambler-ui/Typography/Text' {
  declare module.exports: any;
}

declare module 'rambler-ui/Typography/Timestamp' {
  declare module.exports: any;
}

declare module 'rambler-ui/Typography/Typography' {
  declare module.exports: any;
}

declare module 'rambler-ui/utils/colors' {
  declare module.exports: any;
}

declare module 'rambler-ui/utils/DOM' {
  declare module.exports: any;
}

declare module 'rambler-ui/utils/focus-source' {
  declare module.exports: any;
}

declare module 'rambler-ui/utils/raf' {
  declare module.exports: any;
}

declare module 'rambler-ui/utils/test-utils' {
  declare module.exports: any;
}

declare module 'rambler-ui/utils/uuid' {
  declare module.exports: any;
}

declare module 'rambler-ui/VisibilityAnimation/index' {
  declare module.exports: any;
}

declare module 'rambler-ui/VisibilityAnimation/VisibilityAnimation' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rambler-ui/Avatar/Avatar.js' {
  declare module.exports: $Exports<'rambler-ui/Avatar/Avatar'>;
}
declare module 'rambler-ui/Avatar/index.js' {
  declare module.exports: $Exports<'rambler-ui/Avatar/index'>;
}
declare module 'rambler-ui/Button/Button.js' {
  declare module.exports: $Exports<'rambler-ui/Button/Button'>;
}
declare module 'rambler-ui/Button/index.js' {
  declare module.exports: $Exports<'rambler-ui/Button/index'>;
}
declare module 'rambler-ui/Checkbox/Checkbox.js' {
  declare module.exports: $Exports<'rambler-ui/Checkbox/Checkbox'>;
}
declare module 'rambler-ui/Checkbox/index.js' {
  declare module.exports: $Exports<'rambler-ui/Checkbox/index'>;
}
declare module 'rambler-ui/ComplexSearch/ComplexSearch.js' {
  declare module.exports: $Exports<'rambler-ui/ComplexSearch/ComplexSearch'>;
}
declare module 'rambler-ui/ComplexSearch/index.js' {
  declare module.exports: $Exports<'rambler-ui/ComplexSearch/index'>;
}
declare module 'rambler-ui/ComplexSearch/SuggestItem.js' {
  declare module.exports: $Exports<'rambler-ui/ComplexSearch/SuggestItem'>;
}
declare module 'rambler-ui/constants/context.js' {
  declare module.exports: $Exports<'rambler-ui/constants/context'>;
}
declare module 'rambler-ui/constants/keys.js' {
  declare module.exports: $Exports<'rambler-ui/constants/keys'>;
}
declare module 'rambler-ui/constants/overlay.js' {
  declare module.exports: $Exports<'rambler-ui/constants/overlay'>;
}
declare module 'rambler-ui/constants/z-indexes.js' {
  declare module.exports: $Exports<'rambler-ui/constants/z-indexes'>;
}
declare module 'rambler-ui/Dropdown/Dropdown.js' {
  declare module.exports: $Exports<'rambler-ui/Dropdown/Dropdown'>;
}
declare module 'rambler-ui/Dropdown/index.js' {
  declare module.exports: $Exports<'rambler-ui/Dropdown/index'>;
}
declare module 'rambler-ui/events/OnClickOutside.js' {
  declare module.exports: $Exports<'rambler-ui/events/OnClickOutside'>;
}
declare module 'rambler-ui/FieldGroup/FieldGroup.js' {
  declare module.exports: $Exports<'rambler-ui/FieldGroup/FieldGroup'>;
}
declare module 'rambler-ui/FieldGroup/index.js' {
  declare module.exports: $Exports<'rambler-ui/FieldGroup/index'>;
}
declare module 'rambler-ui/FormGroup/FormGroup.js' {
  declare module.exports: $Exports<'rambler-ui/FormGroup/FormGroup'>;
}
declare module 'rambler-ui/FormGroup/index.js' {
  declare module.exports: $Exports<'rambler-ui/FormGroup/index'>;
}
declare module 'rambler-ui/Hint/Hint.js' {
  declare module.exports: $Exports<'rambler-ui/Hint/Hint'>;
}
declare module 'rambler-ui/Hint/index.js' {
  declare module.exports: $Exports<'rambler-ui/Hint/index'>;
}
declare module 'rambler-ui/hoc/provide-render-to-layer.js' {
  declare module.exports: $Exports<'rambler-ui/hoc/provide-render-to-layer'>;
}
declare module 'rambler-ui/hoc/render-to-layer.js' {
  declare module.exports: $Exports<'rambler-ui/hoc/render-to-layer'>;
}
declare module 'rambler-ui/hoc/window-events.js' {
  declare module.exports: $Exports<'rambler-ui/hoc/window-events'>;
}
declare module 'rambler-ui/hoc/z-index-stack.js' {
  declare module.exports: $Exports<'rambler-ui/hoc/z-index-stack'>;
}
declare module 'rambler-ui/IconButton/IconButton.js' {
  declare module.exports: $Exports<'rambler-ui/IconButton/IconButton'>;
}
declare module 'rambler-ui/IconButton/index.js' {
  declare module.exports: $Exports<'rambler-ui/IconButton/index'>;
}
declare module 'rambler-ui/icons/forms/AddIcon.js' {
  declare module.exports: $Exports<'rambler-ui/icons/forms/AddIcon'>;
}
declare module 'rambler-ui/icons/forms/BlockIcon.js' {
  declare module.exports: $Exports<'rambler-ui/icons/forms/BlockIcon'>;
}
declare module 'rambler-ui/icons/forms/BookIcon.js' {
  declare module.exports: $Exports<'rambler-ui/icons/forms/BookIcon'>;
}
declare module 'rambler-ui/icons/forms/ChevronLeftIcon.js' {
  declare module.exports: $Exports<'rambler-ui/icons/forms/ChevronLeftIcon'>;
}
declare module 'rambler-ui/icons/forms/ChevronRightIcon.js' {
  declare module.exports: $Exports<'rambler-ui/icons/forms/ChevronRightIcon'>;
}
declare module 'rambler-ui/icons/forms/ClearIcon.js' {
  declare module.exports: $Exports<'rambler-ui/icons/forms/ClearIcon'>;
}
declare module 'rambler-ui/icons/forms/ClosedEyeIcon.js' {
  declare module.exports: $Exports<'rambler-ui/icons/forms/ClosedEyeIcon'>;
}
declare module 'rambler-ui/icons/forms/CreditCardIcon.js' {
  declare module.exports: $Exports<'rambler-ui/icons/forms/CreditCardIcon'>;
}
declare module 'rambler-ui/icons/forms/EditIcon.js' {
  declare module.exports: $Exports<'rambler-ui/icons/forms/EditIcon'>;
}
declare module 'rambler-ui/icons/forms/EllipsisIcon.js' {
  declare module.exports: $Exports<'rambler-ui/icons/forms/EllipsisIcon'>;
}
declare module 'rambler-ui/icons/forms/EmailIcon.js' {
  declare module.exports: $Exports<'rambler-ui/icons/forms/EmailIcon'>;
}
declare module 'rambler-ui/icons/forms/Eye.js' {
  declare module.exports: $Exports<'rambler-ui/icons/forms/Eye'>;
}
declare module 'rambler-ui/icons/forms/FaceIcon.js' {
  declare module.exports: $Exports<'rambler-ui/icons/forms/FaceIcon'>;
}
declare module 'rambler-ui/icons/forms/HoldIcon.js' {
  declare module.exports: $Exports<'rambler-ui/icons/forms/HoldIcon'>;
}
declare module 'rambler-ui/icons/forms/index.js' {
  declare module.exports: $Exports<'rambler-ui/icons/forms/index'>;
}
declare module 'rambler-ui/icons/forms/InfoIcon.js' {
  declare module.exports: $Exports<'rambler-ui/icons/forms/InfoIcon'>;
}
declare module 'rambler-ui/icons/forms/KeyboardIcon.js' {
  declare module.exports: $Exports<'rambler-ui/icons/forms/KeyboardIcon'>;
}
declare module 'rambler-ui/icons/forms/LockIcon.js' {
  declare module.exports: $Exports<'rambler-ui/icons/forms/LockIcon'>;
}
declare module 'rambler-ui/icons/forms/LockOpenIcon.js' {
  declare module.exports: $Exports<'rambler-ui/icons/forms/LockOpenIcon'>;
}
declare module 'rambler-ui/icons/forms/LockOutlineIcon.js' {
  declare module.exports: $Exports<'rambler-ui/icons/forms/LockOutlineIcon'>;
}
declare module 'rambler-ui/icons/forms/PhoneIcon.js' {
  declare module.exports: $Exports<'rambler-ui/icons/forms/PhoneIcon'>;
}
declare module 'rambler-ui/icons/forms/PhotoCameraIcon.js' {
  declare module.exports: $Exports<'rambler-ui/icons/forms/PhotoCameraIcon'>;
}
declare module 'rambler-ui/icons/forms/QuestionIcon.js' {
  declare module.exports: $Exports<'rambler-ui/icons/forms/QuestionIcon'>;
}
declare module 'rambler-ui/icons/forms/RefreshIcon.js' {
  declare module.exports: $Exports<'rambler-ui/icons/forms/RefreshIcon'>;
}
declare module 'rambler-ui/icons/forms/RemoveIcon.js' {
  declare module.exports: $Exports<'rambler-ui/icons/forms/RemoveIcon'>;
}
declare module 'rambler-ui/icons/forms/SearchIcon.js' {
  declare module.exports: $Exports<'rambler-ui/icons/forms/SearchIcon'>;
}
declare module 'rambler-ui/icons/forms/SettingsIcon.js' {
  declare module.exports: $Exports<'rambler-ui/icons/forms/SettingsIcon'>;
}
declare module 'rambler-ui/icons/forms/TickIcon.js' {
  declare module.exports: $Exports<'rambler-ui/icons/forms/TickIcon'>;
}
declare module 'rambler-ui/icons/forms/UndoIcon.js' {
  declare module.exports: $Exports<'rambler-ui/icons/forms/UndoIcon'>;
}
declare module 'rambler-ui/icons/forms/WizardIcon.js' {
  declare module.exports: $Exports<'rambler-ui/icons/forms/WizardIcon'>;
}
declare module 'rambler-ui/icons/index.js' {
  declare module.exports: $Exports<'rambler-ui/icons/index'>;
}
declare module 'rambler-ui/icons/profiles/ChampionatIcon.js' {
  declare module.exports: $Exports<'rambler-ui/icons/profiles/ChampionatIcon'>;
}
declare module 'rambler-ui/icons/profiles/FacebookIcon.js' {
  declare module.exports: $Exports<'rambler-ui/icons/profiles/FacebookIcon'>;
}
declare module 'rambler-ui/icons/profiles/GoogleIcon.js' {
  declare module.exports: $Exports<'rambler-ui/icons/profiles/GoogleIcon'>;
}
declare module 'rambler-ui/icons/profiles/index.js' {
  declare module.exports: $Exports<'rambler-ui/icons/profiles/index'>;
}
declare module 'rambler-ui/icons/profiles/InstagramIcon.js' {
  declare module.exports: $Exports<'rambler-ui/icons/profiles/InstagramIcon'>;
}
declare module 'rambler-ui/icons/profiles/LivejournalIcon.js' {
  declare module.exports: $Exports<'rambler-ui/icons/profiles/LivejournalIcon'>;
}
declare module 'rambler-ui/icons/profiles/MailruIcon.js' {
  declare module.exports: $Exports<'rambler-ui/icons/profiles/MailruIcon'>;
}
declare module 'rambler-ui/icons/profiles/OdnoklassnikiIcon.js' {
  declare module.exports: $Exports<'rambler-ui/icons/profiles/OdnoklassnikiIcon'>;
}
declare module 'rambler-ui/icons/profiles/PgumosruIcon.js' {
  declare module.exports: $Exports<'rambler-ui/icons/profiles/PgumosruIcon'>;
}
declare module 'rambler-ui/icons/profiles/PhoneIcon.js' {
  declare module.exports: $Exports<'rambler-ui/icons/profiles/PhoneIcon'>;
}
declare module 'rambler-ui/icons/profiles/RamblerIcon.js' {
  declare module.exports: $Exports<'rambler-ui/icons/profiles/RamblerIcon'>;
}
declare module 'rambler-ui/icons/profiles/TwitterIcon.js' {
  declare module.exports: $Exports<'rambler-ui/icons/profiles/TwitterIcon'>;
}
declare module 'rambler-ui/icons/profiles/VkontakteIcon.js' {
  declare module.exports: $Exports<'rambler-ui/icons/profiles/VkontakteIcon'>;
}
declare module 'rambler-ui/icons/services/index.js' {
  declare module.exports: $Exports<'rambler-ui/icons/services/index'>;
}
declare module 'rambler-ui/icons/services/RamblerAutoIcon.js' {
  declare module.exports: $Exports<'rambler-ui/icons/services/RamblerAutoIcon'>;
}
declare module 'rambler-ui/icons/services/RamblerMailIcon.js' {
  declare module.exports: $Exports<'rambler-ui/icons/services/RamblerMailIcon'>;
}
declare module 'rambler-ui/icons/services/RamblerMoneyIcon.js' {
  declare module.exports: $Exports<'rambler-ui/icons/services/RamblerMoneyIcon'>;
}
declare module 'rambler-ui/icons/SvgIcon/index.js' {
  declare module.exports: $Exports<'rambler-ui/icons/SvgIcon/index'>;
}
declare module 'rambler-ui/icons/SvgIcon/SvgIcon.js' {
  declare module.exports: $Exports<'rambler-ui/icons/SvgIcon/SvgIcon'>;
}
declare module 'rambler-ui/index' {
  declare module.exports: $Exports<'rambler-ui'>;
}
declare module 'rambler-ui/index.js' {
  declare module.exports: $Exports<'rambler-ui'>;
}
declare module 'rambler-ui/Input/index.js' {
  declare module.exports: $Exports<'rambler-ui/Input/index'>;
}
declare module 'rambler-ui/Input/Input.js' {
  declare module.exports: $Exports<'rambler-ui/Input/Input'>;
}
declare module 'rambler-ui/InputStatus/index.js' {
  declare module.exports: $Exports<'rambler-ui/InputStatus/index'>;
}
declare module 'rambler-ui/InputStatus/InputStatus.js' {
  declare module.exports: $Exports<'rambler-ui/InputStatus/InputStatus'>;
}
declare module 'rambler-ui/Loader/index.js' {
  declare module.exports: $Exports<'rambler-ui/Loader/index'>;
}
declare module 'rambler-ui/Loader/Loader.js' {
  declare module.exports: $Exports<'rambler-ui/Loader/Loader'>;
}
declare module 'rambler-ui/Menu/index.js' {
  declare module.exports: $Exports<'rambler-ui/Menu/index'>;
}
declare module 'rambler-ui/Menu/Menu.js' {
  declare module.exports: $Exports<'rambler-ui/Menu/Menu'>;
}
declare module 'rambler-ui/Menu/MenuItem.js' {
  declare module.exports: $Exports<'rambler-ui/Menu/MenuItem'>;
}
declare module 'rambler-ui/Notification/index.js' {
  declare module.exports: $Exports<'rambler-ui/Notification/index'>;
}
declare module 'rambler-ui/Notification/Notification.js' {
  declare module.exports: $Exports<'rambler-ui/Notification/Notification'>;
}
declare module 'rambler-ui/Notification/provideNotification.js' {
  declare module.exports: $Exports<'rambler-ui/Notification/provideNotification'>;
}
declare module 'rambler-ui/Overlay/FixedOverlay.js' {
  declare module.exports: $Exports<'rambler-ui/Overlay/FixedOverlay'>;
}
declare module 'rambler-ui/Overlay/index.js' {
  declare module.exports: $Exports<'rambler-ui/Overlay/index'>;
}
declare module 'rambler-ui/Overlay/RelativeOverlay.js' {
  declare module.exports: $Exports<'rambler-ui/Overlay/RelativeOverlay'>;
}
declare module 'rambler-ui/Pagination/index.js' {
  declare module.exports: $Exports<'rambler-ui/Pagination/index'>;
}
declare module 'rambler-ui/Pagination/Pagination.js' {
  declare module.exports: $Exports<'rambler-ui/Pagination/Pagination'>;
}
declare module 'rambler-ui/Popup/index.js' {
  declare module.exports: $Exports<'rambler-ui/Popup/index'>;
}
declare module 'rambler-ui/Popup/Popup.js' {
  declare module.exports: $Exports<'rambler-ui/Popup/Popup'>;
}
declare module 'rambler-ui/Popup/providePopup.js' {
  declare module.exports: $Exports<'rambler-ui/Popup/providePopup'>;
}
declare module 'rambler-ui/Radio/index.js' {
  declare module.exports: $Exports<'rambler-ui/Radio/index'>;
}
declare module 'rambler-ui/Radio/RadioButton.js' {
  declare module.exports: $Exports<'rambler-ui/Radio/RadioButton'>;
}
declare module 'rambler-ui/Radio/RadioButtonGroup.js' {
  declare module.exports: $Exports<'rambler-ui/Radio/RadioButtonGroup'>;
}
declare module 'rambler-ui/Select/index.js' {
  declare module.exports: $Exports<'rambler-ui/Select/index'>;
}
declare module 'rambler-ui/Select/Select.js' {
  declare module.exports: $Exports<'rambler-ui/Select/Select'>;
}
declare module 'rambler-ui/SideNav/index.js' {
  declare module.exports: $Exports<'rambler-ui/SideNav/index'>;
}
declare module 'rambler-ui/SideNav/SideNav.js' {
  declare module.exports: $Exports<'rambler-ui/SideNav/SideNav'>;
}
declare module 'rambler-ui/SideNav/SideNavItem.js' {
  declare module.exports: $Exports<'rambler-ui/SideNav/SideNavItem'>;
}
declare module 'rambler-ui/Snackbar/index.js' {
  declare module.exports: $Exports<'rambler-ui/Snackbar/index'>;
}
declare module 'rambler-ui/Snackbar/provideSnackbar.js' {
  declare module.exports: $Exports<'rambler-ui/Snackbar/provideSnackbar'>;
}
declare module 'rambler-ui/Snackbar/Snackbar.js' {
  declare module.exports: $Exports<'rambler-ui/Snackbar/Snackbar'>;
}
declare module 'rambler-ui/Spinner/index.js' {
  declare module.exports: $Exports<'rambler-ui/Spinner/index'>;
}
declare module 'rambler-ui/Spinner/Spinner.js' {
  declare module.exports: $Exports<'rambler-ui/Spinner/Spinner'>;
}
declare module 'rambler-ui/style/imports.js' {
  declare module.exports: $Exports<'rambler-ui/style/imports'>;
}
declare module 'rambler-ui/style/mixins.js' {
  declare module.exports: $Exports<'rambler-ui/style/mixins'>;
}
declare module 'rambler-ui/Switcher/index.js' {
  declare module.exports: $Exports<'rambler-ui/Switcher/index'>;
}
declare module 'rambler-ui/Switcher/Switcher.js' {
  declare module.exports: $Exports<'rambler-ui/Switcher/Switcher'>;
}
declare module 'rambler-ui/Tabs/index.js' {
  declare module.exports: $Exports<'rambler-ui/Tabs/index'>;
}
declare module 'rambler-ui/Tabs/Tabs.js' {
  declare module.exports: $Exports<'rambler-ui/Tabs/Tabs'>;
}
declare module 'rambler-ui/Tabs/TabsItem.js' {
  declare module.exports: $Exports<'rambler-ui/Tabs/TabsItem'>;
}
declare module 'rambler-ui/TagsInput/index.js' {
  declare module.exports: $Exports<'rambler-ui/TagsInput/index'>;
}
declare module 'rambler-ui/TagsInput/TagsInput.js' {
  declare module.exports: $Exports<'rambler-ui/TagsInput/TagsInput'>;
}
declare module 'rambler-ui/TagsInput/TagsInputItem.js' {
  declare module.exports: $Exports<'rambler-ui/TagsInput/TagsInputItem'>;
}
declare module 'rambler-ui/Textarea/index.js' {
  declare module.exports: $Exports<'rambler-ui/Textarea/index'>;
}
declare module 'rambler-ui/Textarea/Textarea.js' {
  declare module.exports: $Exports<'rambler-ui/Textarea/Textarea'>;
}
declare module 'rambler-ui/theme/base/colors.js' {
  declare module.exports: $Exports<'rambler-ui/theme/base/colors'>;
}
declare module 'rambler-ui/theme/base/i18n.js' {
  declare module.exports: $Exports<'rambler-ui/theme/base/i18n'>;
}
declare module 'rambler-ui/theme/base/index.js' {
  declare module.exports: $Exports<'rambler-ui/theme/base/index'>;
}
declare module 'rambler-ui/theme/champ/colors.js' {
  declare module.exports: $Exports<'rambler-ui/theme/champ/colors'>;
}
declare module 'rambler-ui/theme/champ/i18n.js' {
  declare module.exports: $Exports<'rambler-ui/theme/champ/i18n'>;
}
declare module 'rambler-ui/theme/champ/index.js' {
  declare module.exports: $Exports<'rambler-ui/theme/champ/index'>;
}
declare module 'rambler-ui/theme/index.js' {
  declare module.exports: $Exports<'rambler-ui/theme/index'>;
}
declare module 'rambler-ui/Toggle/index.js' {
  declare module.exports: $Exports<'rambler-ui/Toggle/index'>;
}
declare module 'rambler-ui/Toggle/Toggle.js' {
  declare module.exports: $Exports<'rambler-ui/Toggle/Toggle'>;
}
declare module 'rambler-ui/Toggle/ToggleOption.js' {
  declare module.exports: $Exports<'rambler-ui/Toggle/ToggleOption'>;
}
declare module 'rambler-ui/Tooltip/index.js' {
  declare module.exports: $Exports<'rambler-ui/Tooltip/index'>;
}
declare module 'rambler-ui/Tooltip/Tooltip.js' {
  declare module.exports: $Exports<'rambler-ui/Tooltip/Tooltip'>;
}
declare module 'rambler-ui/Typography/Description.js' {
  declare module.exports: $Exports<'rambler-ui/Typography/Description'>;
}
declare module 'rambler-ui/Typography/Epigraph.js' {
  declare module.exports: $Exports<'rambler-ui/Typography/Epigraph'>;
}
declare module 'rambler-ui/Typography/GalleryDescription.js' {
  declare module.exports: $Exports<'rambler-ui/Typography/GalleryDescription'>;
}
declare module 'rambler-ui/Typography/H1.js' {
  declare module.exports: $Exports<'rambler-ui/Typography/H1'>;
}
declare module 'rambler-ui/Typography/H2.js' {
  declare module.exports: $Exports<'rambler-ui/Typography/H2'>;
}
declare module 'rambler-ui/Typography/H3.js' {
  declare module.exports: $Exports<'rambler-ui/Typography/H3'>;
}
declare module 'rambler-ui/Typography/index.js' {
  declare module.exports: $Exports<'rambler-ui/Typography/index'>;
}
declare module 'rambler-ui/Typography/List.js' {
  declare module.exports: $Exports<'rambler-ui/Typography/List'>;
}
declare module 'rambler-ui/Typography/PhotoSource.js' {
  declare module.exports: $Exports<'rambler-ui/Typography/PhotoSource'>;
}
declare module 'rambler-ui/Typography/Quote.js' {
  declare module.exports: $Exports<'rambler-ui/Typography/Quote'>;
}
declare module 'rambler-ui/Typography/Source.js' {
  declare module.exports: $Exports<'rambler-ui/Typography/Source'>;
}
declare module 'rambler-ui/Typography/Text.js' {
  declare module.exports: $Exports<'rambler-ui/Typography/Text'>;
}
declare module 'rambler-ui/Typography/Timestamp.js' {
  declare module.exports: $Exports<'rambler-ui/Typography/Timestamp'>;
}
declare module 'rambler-ui/Typography/Typography.js' {
  declare module.exports: $Exports<'rambler-ui/Typography/Typography'>;
}
declare module 'rambler-ui/utils/colors.js' {
  declare module.exports: $Exports<'rambler-ui/utils/colors'>;
}
declare module 'rambler-ui/utils/DOM.js' {
  declare module.exports: $Exports<'rambler-ui/utils/DOM'>;
}
declare module 'rambler-ui/utils/focus-source.js' {
  declare module.exports: $Exports<'rambler-ui/utils/focus-source'>;
}
declare module 'rambler-ui/utils/raf.js' {
  declare module.exports: $Exports<'rambler-ui/utils/raf'>;
}
declare module 'rambler-ui/utils/test-utils.js' {
  declare module.exports: $Exports<'rambler-ui/utils/test-utils'>;
}
declare module 'rambler-ui/utils/uuid.js' {
  declare module.exports: $Exports<'rambler-ui/utils/uuid'>;
}
declare module 'rambler-ui/VisibilityAnimation/index.js' {
  declare module.exports: $Exports<'rambler-ui/VisibilityAnimation/index'>;
}
declare module 'rambler-ui/VisibilityAnimation/VisibilityAnimation.js' {
  declare module.exports: $Exports<'rambler-ui/VisibilityAnimation/VisibilityAnimation'>;
}
